# Importing The Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the Dataset

Here, We have two datasets :
    1. email.csv : Dataset of emails and whether they are spam or not
    2. spamwords.csv : Dataset of spam trigger words.
We have to convert all the letters of spamwords to lower-case as emails.csv is in lower-case.

In [65]:
dataset = pd.read_csv('emails.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [66]:
dataset = pd.read_csv('spamwords.csv')
UpperCaseSpam = dataset.iloc[:,-1].values
LowerCaseSpam = list()
for words in UpperCaseSpam:
    LowerCaseSpam.append(words.lower())
print(LowerCaseSpam)


['act now', 'buy', 'call now', 'click', 'click below', 'click here', 'compare', 'do it today', 'don’t delete', 'free', 'get', 'give it away', 'open', 'opt in', 'order', 'order now', 'print from signature', 'print out and fax', 'see for yourself', 'sign up free today', 'stop', 'unsubscribe', 'visit our website', 'congratulations', 'giving away', 'prize', 'prizes', 'talks about prizes', 'who really wins?', 'win', 'winner', 'won', 'you are a winner!', 'you have been selected', 'you’re a winner!', 'confidentially on all orders', 'order today', 'orders shipped by', 'outstanding values', 'sample', 'wants credit card', 'what are you waiting for?', '“hidden” assets', '$$$', 'additional income', 'apply online', 'avoid bankruptcy', 'be your own boss', 'beneficiary', 'big bucks', 'billion', 'billion dollars', 'calling creditors', 'cash', 'cash bonus', 'cashcashcash', 'casino', 'cents on the dollar', 'check', 'check or money order', 'collect child support', 'consolidate debt and credit', 'consolid

## Making the final list of Input

In [5]:
FinalInput = list()
for sentences in X:
    s = str(sentences)
    count = 0
    for spam_words in LowerCaseSpam:
        if spam_words in s:
            count = count+1
    FinalInput.append(count/len(s))


## Splitting the Dataset into Training and Test Dataset

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(FinalInput, y, test_size = 0.25, random_state = 0)

In [68]:
X_train = np.array(X_train)
X_train = X_train.reshape(len(X_train),1)
X_train

array([[0.01793722],
       [0.00269024],
       [0.00708661],
       ...,
       [0.00468384],
       [0.00519481],
       [0.00675676]])

In [69]:
X_test = np.array(X_test)
X_test = X_test.reshape(len(X_test),1)
X_test

array([[0.00353157],
       [0.00654308],
       [0.01777778],
       ...,
       [0.00754717],
       [0.00305144],
       [0.00537634]])

## Applying Feature Scaling to The Training and the Test Set

In [70]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Using the In-build Library ScikitLearn for Applying Logisitic Regression to our Model 

In [71]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Comparing the Predicted Values and Final Values

In [73]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Checking the Accuracy of the Model  

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1033   56]
 [ 207  136]]


0.8163407821229051